blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/T2VzhzqU67
    about: Ask questions and discuss with other MyButton community members 
  - name: Website
    url: https://openscilab.com
    about: Check out our website for more information
