name: mybutton dev deployment

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v4
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Version Check
        run: |
          python otherfiles/version_check.py
  build:
    runs-on: ubuntu-latest
    needs: version_check
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js 16.15.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - run: |
          yarn install
          yarn build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: craco_build_output
          path: build/**
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: craco_build_output
          path: build
      - run: |
          yarn install
