name: mybutton dev deployment

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Download Code
      - name: Install Node ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies & Build 
        run: |
          yarn install  
          yarn build
